name: flutter_image_test_utils
description: Provides an easier and simple way to test flutter network images.
license: MIT
version: 1.1.0

repository: https://github.com/WillACosta/flutter_image_test_utils
issue_tracker: https://github.com/WillACosta/flutter_image_test_utils/issues
homepage: https://github.com/WillACosta/flutter_image_test_utils
documentation: https://github.com/WillACosta/flutter_image_test_utils

topics:
  - widget-tests
  - flutter
  - network-image

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  mocktail: ^1.0.3

dev_dependencies:
  flutter_lints: ^6.0.0
